name = "SlimWrap"
uuid = "05d209b7-eabf-4a52-afc7-7998cd71eaa4"
authors = ["arzwa <arthur.zwaenepoel@gmail.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
JSON = "0.21.4"
PyCall = "1.96.4"
